services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: rsync -a public/ /data/public/ && yarn start
    healthCheckPath: /_health
    disk:
      name: strapi-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 12.18.4
      - key: NODE_ENV
        value: production
      - key: DATABASE_FILENAME
        value: /.temp/data.db
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: SENDGRID_API_KEY
        value: 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
      - key: API_TOKEN_SALT
        value: 5x8ZhjllXn19lQd9rGDUiw==
      - key: APP_KEYS
        values: WkL4nhx3/Rwun7SaaF2uEA==,K0Lb1bTmh1rbs1FZJ+eiQw==,ifkykCngvOt3nywdJEK59w==,38dIa2iVuQouJh1p5KnFoQ==
